entity_type_groups:
  node:
    fabric:
      basic: basic
      advanced: advanced
      dublin_core: dublin_core
      dublin_core_advanced: dublin_core_advanced
separator: '|'
tag_trim_method: beforeValue
use_maxlength: true
tag_trim_maxlength:
  metatag_maxlength_title: null
  metatag_maxlength_description: null
  metatag_maxlength_abstract: null
  metatag_maxlength_dcterms_title: null
  metatag_maxlength_dcterms_description: null
tag_scroll_max_height: ''
tag_trim_end: '|.,-:;/+&([{"'''
